services:
  api:
    image: node:20-buster
    tty: true
    environment:
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DATABASE=${DB_DATABASE}
    ports:
      - '3001:3000'
    volumes:
      - ./api:/app
    working_dir: /app
    command: bash -c "npm install && npm run start:dev"