services:
  api:
    image: node:20-buster
    tty: true
    environment:
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASS}
      - DB_DATABASE=${DB_NAME}
      - DB_HOST=${DB_HOST}
      - JWT_SECRET=${JWT_SECRET}
      - FRONTEND_URL=${FRONTEND_URL}
      - BACKEND_URL=${BACKEND_URL}
      - GOOGLE_CLIENT_ID=${GOOGLE_CLIENT_ID}
      - GOOGLE_SECRET=${GOOGLE_SECRET}
      - GOOGLE_CALLBACK_URL=${GOOGLE_CALLBACK_URL}
      - GOOGLE_CALLBACK_LINK_URL=${GOOGLE_CALLBACK_LINK_URL}
      - COOKIE_DOMAIN=${COOKIE_DOMAIN}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - REFRESH_TOKEN=${REFRESH_TOKEN}
    ports:
      - "3001:3000"
    volumes:
      - ./api:/app
      - ./files:/files
    working_dir: /app
    command: bash -c "npm install && npm run start:dev"
    networks:
      - backend
  db:
    image: mysql:8.1.0
    environment:
      - MYSQL_USER=${DB_USER}
      - MYSQL_PASSWORD=${DB_PASS}
      - MYSQL_DATABASE=${DB_NAME}
      - MYSQL_ROOT_PASSWORD=${DB_PASS}
      - TZ=Asia/Seoul
    ports:
      - "3307:3306"
    networks:
      - backend

networks:
  backend: