name: Deploy NestJS to EC2
on:
  push:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t koreannestjs ./api/

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image to DockerHub
        run: |
          docker tag koreannestjs ${{ secrets.DOCKER_USERNAME }}/koreannestjs:latest
          docker push ${{ secrets.DOCKER_USERNAME }}/koreannestjs:latest

      - name: SSH to EC2 and deploy
        uses: appleboy/ssh-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_PRIVATE_KEY }}
          script: |
            docker pull ${{ secrets.DOCKER_USERNAME }}/koreannestjs:latest
            docker stop koreannestjs || true
            docker rm koreannestjs || true
            docker run -d -p 3000:3000 --name koreannestjs \
            -e FRONTEND_URL=${{ secrets.FRONTEND_URL }} \
            -e DB_USER=${{ secrets.DB_USERNAME }} \
            -e DB_PASSWORD=${{ secrets.DB_PASSWORD }} \
            -e DB_HOST=${{ secrets.DB_HOST }} \
            -e DB_DATABASE=${{ secrets.DB_DATABASE }} \
            -e JWT_SECRET=${{ secrets.JWT_SECRET }} \
            -e EMAIL_USER=${{ secrets.EMAIL_USER }} \
            -e EMAIL_PASS=${{ secrets.EMAIL_PASS }} \
            -e BACKEND_URL=${{ secrets.BACKEND_URL }} \
            -e GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }} \
            -e GOOGLE_SECRET=${{ secrets.GOOGLE_SECRET }} \
            -e GOOGLE_CALLBACK_URL=${{ secrets.GOOGLE_CALLBACK_URL }} \
            -e GOOGLE_CALLBACK_LINK_URL=${{ secrets.GOOGLE_CALLBACK_LINK_URL }} \
            -e BACKEND_URL=${{ secrets.BACKEND_URL }} \
            -e COOKIE_DOMAIN=${{ secrets.COOKIE_DOMAIN }} \
            -v ~/files:/files \
            ${{ secrets.DOCKER_USERNAME }}/koreannestjs:latest
